parameters:
  doctrine_mappings:
    User:
      dir: '%kernel.project_dir%/src/Slink/User/Infrastructure/ReadModel/View'
      prefix: 'Slink\User\Infrastructure\ReadModel\View'
    Image:
      dir: '%kernel.project_dir%/src/Slink/Image/Infrastructure/ReadModel/View'
      prefix: 'Slink\Image\Infrastructure\ReadModel\View'
    ImageEmbedded:
      dir: '%kernel.project_dir%/src/Slink/Image/Domain/ValueObject'
      prefix: 'Slink\Image\Domain\ValueObject'
    Tag:
      dir: '%kernel.project_dir%/src/Slink/Tag/Infrastructure/ReadModel/View'
      prefix: 'Slink\Tag\Infrastructure\ReadModel\View'
    Settings:
      dir: '%kernel.project_dir%/src/Slink/Settings/Infrastructure/ReadModel/View'
      prefix: 'Slink\Settings\Infrastructure\ReadModel\View'
    Comment:
      dir: '%kernel.project_dir%/src/Slink/Comment/Infrastructure/ReadModel/View'
      prefix: 'Slink\Comment\Infrastructure\ReadModel\View'
